
## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/post"
  to = "/post"
  status = 200
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/post/:id"
  to = "/post/:id"
  status = 200
  force = true
  query = {id = ":id"}
  

  [[redirects]]
  from = "/list"
  to = "https://rollingpaper-team6.netlify.app/list"
  status = 200

  [[redirects]]
  from = "/post/:id/edit"
  to = "/post/:id/edit"
  status = 200
  force = true
  query = {id = ":id"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}

[[redirects]]
  from = "/test"
  to = "https://www.naver.com/"
  status = 200
  force = true
  

[[redirects]]
  from = "/*"
  to = "/*"
  status = 200
  force = true
  query = {path = ":path"}
  